name: Build and Release OmniScreen

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 📥 Telechargement du code source
      uses: actions/checkout@v4

    - name: 🐍 Installation de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: 📦 Installation des modules
      shell: powershell
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: 🔨 Compilation de l'Executable
      shell: powershell
      run: |
        pyinstaller --noconfirm --onedir --windowed --name "OmniScreen" --hidden-import PyQt5.QtWebEngineWidgets --add-data "cms/templates;cms/templates" --add-data "version.txt;." "launcher.py"
        
    - name: 📁 Copie des dossiers
      shell: powershell
      run: |
        mkdir "dist\OmniScreen\config"
        xcopy /E /I /Y "player\config\*" "dist\OmniScreen\config\"

    - name: 💿 Creation de l'Installeur
      shell: powershell
      run: |
        iscc setup.iss

    - name: 🚀 Lecture de la version
      id: get_version
      shell: powershell
      run: |
        $version = Get-Content version.txt
        $version = $version.Trim()
        echo "VERSION=$version" >> $env:GITHUB_ENV

    - name: 🔍 Debug - Verifier si le EXE existe
      shell: powershell
      run: |
        dir InstallerFinal

    - name: 🌐 Publication de la Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.VERSION }}
        name: OmniScreen Mise a jour v${{ env.VERSION }}
        files: InstallerFinal/*.exe  # Utilisation d'un joker (*) au cas ou le nom differe legerement
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
