name: Build and Release OmniScreen

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 📥 Telechargement du code source
      uses: actions/checkout@v4

    - name: 🐍 Installation de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: 🔧 Renommage des fichiers (Si traduits par le navigateur)
      shell: powershell
      run: |
        if (Test-Path "lanceur.py") { Rename-Item "lanceur.py" "launcher.py" -Force }
        if (Test-Path "configuration.iss") { Rename-Item "configuration.iss" "setup.iss" -Force }
        if (Test-Path "joueur") { Rename-Item "joueur" "player" -Force }

    - name: 📦 Installation des modules (pip)
      shell: powershell
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: 🔨 Compilation de l'Executable
      shell: powershell
      run: |
        pyinstaller --noconfirm --onedir --windowed --name "OmniScreen" --hidden-import PyQt5.QtWebEngineWidgets --add-data "cms/templates;cms/templates" --add-data "version.txt;." "launcher.py"
        
    - name: 📁 Copie des dossiers de configuration
      shell: powershell
      run: |
        mkdir "dist\OmniScreen\config"
        xcopy /E /I /Y "player\config\*" "dist\OmniScreen\config\"

    - name: 💿 Creation de l'Installeur (Inno Setup)
      shell: powershell
      run: |
        iscc setup.iss

    - name: 🚀 Lecture de la version
      id: get_version
      shell: powershell
      run: |
        $version = Get-Content version.txt
        $version = $version.Trim()
        echo "VERSION=$version" >> $env:GITHUB_ENV

    # ============================================================
    # NOUVEAUTE POUR L'ECRASEMENT : ON SUPPRIME L'ANCIENNE VERSION
    # ============================================================
    - name: 🗑️ Suppression de l'ancienne Release v${{ env.VERSION }} si elle existe
      uses: dev-drprasad/delete-tag-and-release@v1.1
      with:
        delete_release: true
        tag_name: v${{ env.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 🌐 Publication de la Release (Ecrasement)
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.VERSION }}
        name: OmniScreen Mise a jour v${{ env.VERSION }}
        files: InstallerFinal/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
